### ISSUE TITLE
Bug: Sequence is not defined when trying to open openapi schema 

### ISSUE THREAD

**Issue by noamsto** [litestar-org/advanced-alchemy#272] opened 2024-10-28 10:37 UTC
### Description

Running the code with  `advanced-alchemy==0.21.1` works with no issues.

### Screenshots

![image](https://github.com/user-attachments/assets/b74d1996-6ebb-4807-8b85-c663a7a7a999)

### Logs

```bash
2024-10-28T10:32:38.706789Z [error    ] Uncaught exception             connection_type=http path=/docs
╭───────────────────── Traceback (most recent call last) ──────────────────────╮
│ /home/noams/Data/git/factify-dal/.devenv/state/venv/lib/python3.12/site-pack │
│ ages/litestar/middleware/_internal/exceptions/middleware.py:159 in __call__  │
│                                                                              │
│   156 │   │   │   await send(event)                                          │
│   157 │   │                                                                  │
│   158 │   │   try:                                                           │
│ ❱ 159 │   │   │   await self.app(scope, receive, capture_response_started)   │
│   160 │   │   except Exception as e:                                         │
│   161 │   │   │   if scope_state.response_started:                           │
│   162 │   │   │   │   raise LitestarException("Exception caught after respon │
│                                                                              │
│ /home/noams/Data/git/factify-dal/.devenv/state/venv/lib/python3.12/site-pack │
│ ages/litestar/routes/http.py:80 in handle                                    │
│                                                                              │
│    77 │   │   if route_handler.resolve_guards():                             │
│    78 │   │   │   await route_handler.authorize_connection(connection=reques │
│    79 │   │                                                                  │
│ ❱  80 │   │   response = await self._get_response_for_request(               │
│    81 │   │   │   scope=scope, request=request, route_handler=route_handler, │
│    82 │   │   )                                                              │
│    83                                                                        │
│                                                                              │
│                           ... 22 frames hidden ...                           │
│                                                                              │
│ /nix/store/6g2f4nhh8hjppyz8paxhsxjgs9m4m1kd-python3-3.12.7/lib/python3.12/ty │
│ ping.py:947 in _evaluate                                                     │
│                                                                              │
│    944 │   │   │   │   │   │   localns.pop(param_name, None)                 │
│    945 │   │   │                                                             │
│    946 │   │   │   type_ = _type_check(                                      │
│ ❱  947 │   │   │   │   eval(self.__forward_code__, globalns, localns),       │
│    948 │   │   │   │   "Forward references must evaluate to types.",         │
│    949 │   │   │   │   is_argument=self.__forward_is_argument__,             │
│    950 │   │   │   │   allow_special_forms=self.__forward_is_class__,        │
│ in <module>:1                                                                │
╰──────────────────────────────────────────────────────────────────────────────╯
NameError: name 'Sequence' is not defined

INFO:     127.0.0.1:42330 - "GET /docs HTTP/1.1" 500 Internal Server Error
```

### Package Version

v0.22.0

### Platform

- [X] Linux
- [ ] Mac
- [ ] Windows
- [ ] Other (Please specify in the description above)

**Comment by cofin** [comment] 2024-10-28 16:55
@noamsto can you add some info about what your endpoint looks like that raised this?  I'm not able to reproduce it.  

You can also try what has been merged into master and let me know if this changes the behavior.

**Comment by noamsto** [comment] 2024-10-28 18:08
@cofin thanks for the quick response.
After further investigations, it's the pagination response. 
Opened a PR.

**Closed** 2024-10-28 18:36 UTC
Labels: bug
